"""Crear columna pais en usuario

Revision ID: 475b26d050a5
Revises: eccc9243067f
Create Date: 2022-07-31 22:56:07.006598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '475b26d050a5'
down_revision = 'eccc9243067f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('pais', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario', 'pais')
    # ### end Alembic commands ###
